### ISSUE TITLE
[ERROR] trainprocess_service.py:1109 - Step map_your_entity_network failed

### ISSUE THREAD

**Issue by weilirs** [mindverse/Second-Me#348]
### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows

### Deployment Method

- [x] Docker
- [ ] non-Docker

### CUDA Usage

- [ ] Yes
- [x] No

### Training Process Details (if applicable)

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/95b3ee08-b5f2-4209-8c88-089528ecadd0" />

### Second-Me version

latest master

### Describe the bug

At the training stage, I saw this error in the logs and the training stopped. I tried resume training but didn't work.

### Current Behavior

2025-05-12 19:25:34 [INFO] embedding_service.py:30 - Detected embedding dimension: 1536 for model: text-embedding-ada-002
2025-05-12 19:25:34 [INFO] embedding_service.py:30 - Detected embedding dimension: 1536 for model: text-embedding-ada-002
2025-05-12 19:25:34 [INFO] embedding_service.py:30 - Detected embedding dimension: 1536 for model: text-embedding-ada-002
2025-05-12 19:25:34 [INFO] embedding_service.py:30 - Detected embedding dimension: 1536 for model: text-embedding-ada-002
2025-05-12 19:35:01 [INFO] routes.py:54 - Training process starting...
2025-05-12 19:35:01 [INFO] routes.py:71 - Training parameters: model_name=Qwen2.5-1.5B-Instruct, learning_rate=0.0001, number_of_epochs=2, concurrency_threads=2, data_synthesis_mode=medium, is_cot=False
2025-05-12 19:35:01 [INFO] routes.py:104 - Saved training parameters: {'model_name': 'Qwen2.5-1.5B-Instruct', 'learning_rate': 0.0001, 'number_of_epochs': 2, 'concurrency_threads': 2, 'data_synthesis_mode': 'medium', 'use_cuda': False, 'is_cot': False}
2025-05-12 19:35:01 [INFO] trainprocess_service.py:1078 - Training process started with PID: 26
2025-05-12 19:35:01 [INFO] trainprocess_service.py:1096 - Starting step: map_your_entity_network
2025-05-12 19:35:01 [INFO] trainprocess_service.py:294 - Starting entity network mapping...
2025-05-12 19:35:01 [INFO] trainprocess_service.py:460 - Preparing L2 data...
2025-05-12 19:35:01 [INFO] trainprocess_service.py:472 - Topics data not found, generating it...
2025-05-12 19:35:01 [INFO] trainprocess_service.py:479 - Notes not found, preparing them...
2025-05-12 19:35:01 [INFO] document_service.py:355 - list_documents len: 3
2025-05-12 19:35:01 [INFO] document_service.py:310 - Found 1 chunks for document 1
2025-05-12 19:35:01 [INFO] document_service.py:364 - success getting L0 data for document 1 success
2025-05-12 19:35:01 [INFO] document_service.py:310 - Found 1 chunks for document 2
2025-05-12 19:35:01 [INFO] document_service.py:364 - success getting L0 data for document 2 success
2025-05-12 19:35:01 [INFO] document_service.py:310 - Found 1 chunks for document 3
2025-05-12 19:35:01 [INFO] document_service.py:364 - success getting L0 data for document 3 success
2025-05-12 19:35:01 [INFO] trainprocess_service.py:481 - list_documents_with_l0 len: 3
2025-05-12 19:35:02 [INFO] document_service.py:310 - Found 1 chunks for document 1
2025-05-12 19:35:02 [INFO] document_service.py:310 - Found 1 chunks for document 2
2025-05-12 19:35:02 [INFO] document_service.py:310 - Found 1 chunks for document 3
2025-05-12 19:35:02 [INFO] trainprocess_service.py:483 - extract_notes_from_documents len: 3
2025-05-12 19:35:02 [INFO] trainprocess_service.py:505 - Loading user information...
2025-05-12 19:35:02 [INFO] data.py:340 - Subjective notes: 3, Objective notes: 0
2025-05-12 19:35:02 [INFO] data.py:385 - Refined subjective notes: 3
2025-05-12 19:35:02 [INFO] data.py:429 - Refined objective notes: 0
2025-05-12 19:35:02 [INFO] data.py:461 - Removed existing file: /app/resources/L1/processed_data/subjective/note_remade.json
2025-05-12 19:35:02 [INFO] data.py:461 - Removed existing file: /app/resources/L1/processed_data/subjective/note_1.txt
2025-05-12 19:35:02 [INFO] data.py:461 - Removed existing file: /app/resources/L1/processed_data/subjective/note_0.txt
2025-05-12 19:35:02 [INFO] data.py:461 - Removed existing file: /app/resources/L1/processed_data/subjective/note_2.txt
2025-05-12 19:35:02 [INFO] data.py:465 - Cleared all existing files in /app/resources/L1/processed_data/subjective
2025-05-12 19:35:02 [INFO] data.py:461 - Removed existing file: /app/resources/L1/processed_data/objective/note_remade.json
2025-05-12 19:35:02 [INFO] data.py:465 - Cleared all existing files in /app/resources/L1/processed_data/objective
2025-05-12 19:35:02 [INFO] data.py:103 - Data refinement completed, preparing to extract entities and relations
2025-05-12 19:35:02 [INFO] data.py:546 - Input base_dir has been updated to /app/resources/L1/processed_data/subjective and saved.
2025-05-12 19:35:02 [INFO] data.py:547 - Output base_dir has been updated to /app/resources/L1/graphrag_indexing_output/subjective and saved.
2025-05-12 19:35:02 [INFO] data.py:548 - Report base_dir has been updated to /app/resources/L1/graphrag_indexing_output/subjective/report and saved.
2025-05-12 19:35:02 [ERROR] trainprocess_service.py:309 - Map entity network failed: Command '['bash', '/app/lpm_kernel/L2/data_pipeline/data_prep/scripts/graphrag_indexing.sh']' returned non-zero exit status 2.
2025-05-12 19:35:02 [INFO] trainprocess_service.py:387 - Cleaning up resources to prevent memory leaks
2025-05-12 19:35:02 [INFO] trainprocess_service.py:401 - Memory usage after cleanup: 575.83 MB
2025-05-12 19:35:02 [ERROR] trainprocess_service.py:1109 - Step map_your_entity_network failed
2025-05-12 19:35:02 [INFO] trainprocess_service.py:1110 - Marking step as failed: stage=map_your_entity_network, step=map_your_entity_network

### Expected Behavior

finish training with no errors.

### Reproduction Steps

1. `make docker-up`
2. uploaded 3 text-based memories
3. start training

**Comment by littleGnAl** [comment]
Same error here. Any suggestions to fix it?

**Comment by kevin-mindverse** [comment]
Hi, we've encounter the same issue yesterday. now it's already solved (in our case) fixed in latest version of master.
Plz pull the latest version of code, and try to rebuild it. 

try `make docker-restart-all` if u're using docker :)
@littleGnAl @weilirs

**Comment by littleGnAl** [comment]
@kevin-mindverse 
Thanks, it works for me now.

**Comment by kevin-mindverse** [comment]
yes, well you need to pull the code first. 
try to print the commit id `git rev-parse HEAD`, it'll show `179c52ec18422102ad12b078c171feb294a512ba`
@weilirs

**Comment by AnwithaParuchuri** [comment]
Any suggestions to fix this error, I am still facing it with the latest pull.
